2022-04-17 01:15:03,543 INFO    MainThread:2604807 [wandb_setup.py:_flush():75] Loading settings from /home/z37mao/.config/wandb/settings
2022-04-17 01:15:03,543 INFO    MainThread:2604807 [wandb_setup.py:_flush():75] Loading settings from /home/z37mao/Genova/wandb/settings
2022-04-17 01:15:03,543 INFO    MainThread:2604807 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-17 01:15:03,543 INFO    MainThread:2604807 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-04-17 01:15:03,543 INFO    MainThread:2604807 [wandb_init.py:_log_setup():405] Logging user logs to /home/z37mao/Genova/wandb/run-20220417_011503-3ut61njf/logs/debug.log
2022-04-17 01:15:03,543 INFO    MainThread:2604807 [wandb_init.py:_log_setup():406] Logging internal logs to /home/z37mao/Genova/wandb/run-20220417_011503-3ut61njf/logs/debug-internal.log
2022-04-17 01:15:03,543 INFO    MainThread:2604807 [wandb_init.py:init():439] calling init triggers
2022-04-17 01:15:03,543 INFO    MainThread:2604807 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-04-17 01:15:03,543 INFO    MainThread:2604807 [wandb_init.py:init():458] re-initializing run, found existing run on stack: 1r1hou07
2022-04-17 01:15:03,544 INFO    MainThread:2604807 [wandb_run.py:finish():1539] finishing run amadeusandiris/Genova/1r1hou07
2022-04-17 01:15:03,545 ERROR   MainThread:2604807 [jupyter.py:save_history():421] Run pip install nbformat to save notebook history
2022-04-17 01:15:03,545 INFO    MainThread:2604807 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-04-17 01:15:03,545 INFO    MainThread:2604807 [wandb_init.py:_jupyter_teardown():337] cleaning up jupyter logic
2022-04-17 01:15:03,545 INFO    MainThread:2604807 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-04-17 01:15:03,547 INFO    MainThread:2604807 [wandb_run.py:_restore():1674] restore
2022-04-17 01:15:03,939 INFO    MainThread:2604807 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 869
}

2022-04-17 01:15:04,080 INFO    MainThread:2604807 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 869
}

2022-04-17 01:15:04,199 INFO    MainThread:2604807 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 869
}

2022-04-17 01:15:04,764 INFO    MainThread:2604807 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 15619
}

2022-04-17 01:15:04,866 INFO    MainThread:2604807 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 15619
}

2022-04-17 01:15:04,969 INFO    MainThread:2604807 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 13268
  total_bytes: 15619
}

2022-04-17 01:15:05,071 INFO    MainThread:2604807 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 13268
  total_bytes: 15619
}

2022-04-17 01:15:05,175 INFO    MainThread:2604807 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 13268
  total_bytes: 15619
}

2022-04-17 01:15:05,278 INFO    MainThread:2604807 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 13268
  total_bytes: 15619
}

2022-04-17 01:15:05,380 INFO    MainThread:2604807 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 15619
  total_bytes: 15619
}

2022-04-17 01:15:05,483 INFO    MainThread:2604807 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 15619
  total_bytes: 15619
}

2022-04-17 01:15:05,585 INFO    MainThread:2604807 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 15619
  total_bytes: 15619
}

2022-04-17 01:15:05,688 INFO    MainThread:2604807 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 15619
  total_bytes: 15619
}

2022-04-17 01:15:05,939 INFO    MainThread:2604807 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 15619
  total_bytes: 15619
}

2022-04-17 01:15:06,226 INFO    MainThread:2604807 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 15619
  total_bytes: 15619
}
local_info {
}

2022-04-17 01:15:07,925 INFO    MainThread:2604807 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-04-17 01:15:07,925 INFO    MainThread:2604807 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-04-17 01:15:07,928 INFO    MainThread:2604807 [wandb_run.py:_footer_sync_info():2822] logging synced files
2022-04-17 01:15:07,933 INFO    MainThread:2604807 [wandb_init.py:init():492] starting backend
2022-04-17 01:15:07,933 INFO    MainThread:2604807 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-17 01:15:07,937 INFO    MainThread:2604807 [backend.py:ensure_launched():219] starting backend process...
2022-04-17 01:15:07,988 INFO    MainThread:2604807 [backend.py:ensure_launched():224] started backend process with pid: 2627594
2022-04-17 01:15:07,989 INFO    MainThread:2604807 [wandb_init.py:init():501] backend started and connected
2022-04-17 01:15:07,999 INFO    MainThread:2604807 [wandb_run.py:_label_probe_notebook():947] probe notebook
2022-04-17 01:15:07,999 INFO    MainThread:2604807 [wandb_run.py:_label_probe_notebook():957] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-04-17 01:15:07,999 INFO    MainThread:2604807 [wandb_init.py:init():565] updated telemetry
2022-04-17 01:15:08,116 INFO    MainThread:2604807 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-04-17 01:15:08,754 INFO    MainThread:2604807 [wandb_run.py:_on_init():1759] communicating current version
2022-04-17 01:15:08,791 INFO    MainThread:2604807 [wandb_run.py:_on_init():1763] got version response upgrade_message: "wandb version 0.12.14 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-04-17 01:15:08,791 INFO    MainThread:2604807 [wandb_init.py:init():625] starting run threads in backend
2022-04-17 01:15:13,803 INFO    MainThread:2604807 [wandb_run.py:_console_start():1733] atexit reg
2022-04-17 01:15:13,803 INFO    MainThread:2604807 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-04-17 01:15:13,803 INFO    MainThread:2604807 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-04-17 01:15:13,805 INFO    MainThread:2604807 [wandb_run.py:_redirect():1667] Redirects installed.
2022-04-17 01:15:13,805 INFO    MainThread:2604807 [wandb_init.py:init():664] run started, returning control to user process
2022-04-17 01:15:41,130 INFO    MainThread:2604807 [wandb_watch.py:watch():47] Watching
2022-04-17 01:19:52,173 INFO    MainThread:2604807 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-04-17 01:19:52,180 INFO    MainThread:2604807 [wandb_run.py:_restore():1674] restore
2022-04-17 01:19:53,139 INFO    MainThread:2604807 [wandb_run.py:_restore():1674] restore
